name: user_repository
description: "The repo that handles users."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  
  # cupertino_icons: ^1.0.8
  # google_fonts: ^6.2.1
  firebase_auth: ^5.3.3
  # firebase_core: ^3.8.0
  # firebase_storage: ^12.3.6
  # flutter_easyloading: ^3.0.5
  # flutter_form_builder:
  # form_builder_validators: ^11.0.0
  # pinput: ^5.0.0
  # flutter_svg: ^2.0.16
  # build_runner: ^2.4.13
  # flutter_native_splash: ^2.4.3
  cloud_firestore: ^5.5.0
  rxdart: ^0.27.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  freezed: ^2.5.7

flutter:
  uses-material-design: true
