name: big_bites
description: "Big Bites - A Canteen Management App"
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.5.2
  
dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.2.2
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  firebase_auth: ^5.3.3
  firebase_core: ^3.8.0
  firebase_storage: ^12.3.6
  flutter_easyloading: ^3.0.5
  flutter_form_builder:
  form_builder_validators: ^11.0.0
  pinput: ^5.0.0
  flutter_svg: ^2.0.16
  build_runner: ^2.4.13
  flutter_native_splash: ^2.4.3
  cloud_firestore: ^5.5.0
  fluttertoast: ^8.1.0
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  email_auth: ^2.0.0
  file_picker: ^8.1.4
  image_picker: ^1.1.2
  random_string: ^2.3.1
  shared_preferences: ^2.3.3
  shared_preferences_helper: ^0.0.3
  intl: ^0.19.0
  esewa_flutter_sdk:
    path: ./eSewa_Flutter_Sdk_2.3.0_16/eSewa_Flutter_Sdk_2.3.0_16/esewa_flutter_sdk


  # user_repository:
  #   path: packages/user_repository



flutter_native_splash:
  color: "#ffffff"
  color_dark: "#010101"
  image: assets/images/app_logo.png
  android_12:
    color: "#ffffff"
    color_dark: "#010101"
    image: assets/images/splash/BigBites.png
  android: true
  ios: true

dev_dependencies:
  flutter_native_splash: ^2.4.3
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  freezed: ^2.5.7

flutter:
  uses-material-design: true


  assets:
  - assets/images/splash/
  - assets/images/splash/BigBitesZoom.png
  - assets/icons/user_selected.png
  - assets/icons/user_unselected.png
  - assets/images/choose_to_sign_in/
  - assets/images/sign_in/
  - assets/images/create_an_account/
  - assets/images/welcome/
  - assets/images/detail_page/
  - assets/images/organization_code/
  - assets/images/otp_confirmation/
  - assets/icons/
  - assets/images/
