// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjsZbglgEX3bSsrZ9V2R_EhP-7_y2yoNk',
    appId: '1:897366092723:web:6fc5c8cda797789ec6f9c6',
    messagingSenderId: '897366092723',
    projectId: 'big-bites-c4f08',
    authDomain: 'big-bites-c4f08.firebaseapp.com',
    storageBucket: 'big-bites-c4f08.firebasestorage.app',
    measurementId: 'G-X2D1PRZ31V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDti0ZByxHaEE820x2MxhK-ovKs13XpBr4',
    appId: '1:897366092723:android:20c8df530fbf03ddc6f9c6',
    messagingSenderId: '897366092723',
    projectId: 'big-bites-c4f08',
    storageBucket: 'big-bites-c4f08.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBifsEWtaPXw3wLMH61ujO1Bgz7udiDvP8',
    appId: '1:897366092723:ios:6f7973edf6f7997cc6f9c6',
    messagingSenderId: '897366092723',
    projectId: 'big-bites-c4f08',
    storageBucket: 'big-bites-c4f08.firebasestorage.app',
    iosBundleId: 'com.example.bigBites',
  );

}